### ISSUE TITLE
Unable to start angr-management in docker image?

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr-management#18]
Hello,
I have been trying to open angr-management using the provided docker image but have been unable to start it. After starting with "sudo docker run -it angr/angr", I have run 'python -m angrmanagement' and 'python -m angr-management' in several directories (~, angr-dev, angr-management, angrmanagement) but am met with the same error[s]: "/home/angr/.virtualenvs/angr/bin/python: No module named [angrmanagement/angr-management]"

In case angr-management wasn't installed correctly, I attempted "pip install angr-managment" in the angr docker, but there was an error during the 'Running setup.py' step (ImportError: No module named _markerlib) and "Failed building wheel for distribute" but every other step succeeded. "python -m angrmanagement" then produced "qt_application.pyc: cannot connect to X server" so I suppose that wasn't the right fix either.

How would you recommend proceeding from here?

**Comment by rhelmot** [comment]
I don't know about the installation situation with angr-management, but the "cannot connect to X server" error sounds like that's on the right track. You probably need to pass some extra flags to Docker in order to allow X connections into and out of your container.

**Comment by Dinatrix** [comment]
After a bit of googling, I resolved enough errors to allow angr-management to start up, but when I tried to 'File' > 'Open' or 'Load a new binary' there was an AttributeError that can be seen in this screenshot:
![angrmanage](https://cloud.githubusercontent.com/assets/10760263/22951477/49fb8bfe-f2d7-11e6-9b9f-538b2eaa859b.png)
Which looks to be similar to this issue : https://github.com/angr/angr-management/issues/15
but I am not seeing a 'setuptools.find_packages', just a 'setup.py's in the angr and angr-management folders?

**Comment by ltfish** [comment]
@Dinatrix that's a bug in PySide, or related to the way that `QMainWindow` is implemented in enaml. It's not a bug in angr management (surprising!). An easy workaround (before I spend a day to resolve this issue after this Thursday) is to switch to PyQt by specifying an environmental variable: `QTAPI=pyqt`.

For more information (in case you want to debug enaml and PySide by yourself), please see [here](https://github.com/nucleic/enaml/pull/111), [here](https://github.com/nucleic/enaml/issues/108) and [here](https://github.com/frmdstryr/enaml/commit/c9cebd72ac6152217ac8a0689a882576c240ba31).

PS: I'm still trying my best to not ship an angr-specific version of enaml with angr management, but it seems more and more inevitable.

**Comment by ltfish** [comment]
And I strongly suggest you to use development install for angr management, instead of installing it through pip. I won't have time to make sure the angr management package on PyPI works fine before solving all critical issues in angr management.

**Comment by ltfish** [comment]
Hi, we just pushed a new version onto GitHub which is a totally rewritten from scratch. Do you want to try it out in your docker container?

**Comment by Dinatrix** [comment]
When I tried to launch angr-management in both the latest docker and most up to date angr-dev that is on github (in a new virtualenv as well), I run into an ImportError that there is "No module named PySide.QtGui"

I tried installing pyside as well which did not fix the problem. I made sure to 'export QTAPI=pyqt' and checked that the environment variable was set with 'printenv'.

Should I be setting this environment variable in a different way?

**Comment by ltfish** [comment]
We do not rely on enaml anymore, which means the environmental variable `QTAPI` is not used, and for licensing issues, we only support PySide (not PyQt). You have to install PySide in order to use angr-management.

PySide can be installed via pip: `pip install pyside`. It can take a while to compile, since it only uses one core. Alternatively, you can download PySide and compile it by yourself with `make -jN` to use all your cores, which is significantly faster.

**Comment by stoeps13** [comment]
On my Linux box I can run angr-management with:

`docker run -it --name angr-mgmt --env QT_X11_NO_MITSHM=1 -e DISPLAY=$DISPLAY -v $PWD:/home/angr/pwd -v /tmp/.X11-unix:/tmp/.X11-unix angr/angr-management`

I map the directory where I start the container to `/home/angr/pwd`, so I can access the local files within the container. Maybe you can add that to the documentation and to Docker hub, I needed some time to get all parameters in the right way.

With --name I can start the container again with `docker start angr-mgmt` or you run with `--rm` instead, then you can a clean container each time you run it and when the container stops it gets deleted automatically.
